services:
    postgres:
        image: postgis/postgis:17-3.5-alpine
        container_name: esteemo-postgres
        ports:
            - '5454:5432'
        environment:
            POSTGRES_PASSWORD: mysecretpassword
            POSTGIS_GDAL_ENABLED_DRIVERS: ENABLE_ALL

    keycloak:
        container_name: esteemo-keycloak
        image: quay.io/keycloak/keycloak:26.0.6
        command:
            - start-dev
            - --import-realm
        ports:
            - 8081:8080
        volumes:
            - ./realm-config/:/opt/keycloak/data/import/
        environment:
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: admin
            KC_HTTP_PORT: 8080
            KC_HOSTNAME_URL: http://localhost:8081
            KC_HOSTNAME_ADMIN_URL: http://localhost:8081
            KC_HOSTNAME_STRICT_BACKCHANNEL: true
            KC_HTTP_RELATIVE_PATH: /
            KC_HTTP_ENABLED: true
            KC_HEALTH_ENABLED: true
            KC_METRICS_ENABLED: true
        extra_hosts:
            - "host.docker.internal:host-gateway"
        healthcheck:
            test: [ 'CMD-SHELL', '[ -f /tmp/HealthCheck.java ] || echo "public class HealthCheck { public static void main(String[] args) throws java.lang.Throwable { System.exit(java.net.HttpURLConnection.HTTP_OK == ((java.net.HttpURLConnection)new java.net.URL(args[0]).openConnection()).getResponseCode() ? 0 : 1); } }" > /tmp/HealthCheck.java && java /tmp/HealthCheck.java http://localhost:8080/auth/health/live' ]
            interval: 5s
            timeout: 5s
            retries: 20

